export default [
  {
    id: 1,
    title: "Luxury Condo Near Central Park",
    description:
      "A luxurious condo with breathtaking park views and modern amenities.",
    type: "condo",
    price: 350000,
    location: "Central Park, New York",
    latitude: 40.7812,
    longitude: -73.9665,
    size: 1500,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://example.com/penthouse1.jpg",
      "https://example.com/penthouse1.jpg",
    ],
  },
  {
    id: 2,
    title: "Cozy Cabin in the Mountains. Cozy Cabin in the Mountains",
    description:
      "A quiet cabin in the mountains with scenic views and cozy interiors.",
    type: "cabin",
    price: 120000,
    location: "Aspen, Colorado",
    latitude: 39.1911,
    longitude: -106.8175,
    size: 800,
    bedrooms: 2,
    bathrooms: 1,
    images: [
      "",
    ],
  },
  {
    id: 3,
    title: "Beachfront Villa with Private Pool",
    description:
      "A stunning villa on the beach with a private pool and ocean views.",
    type: "villa",
    price: 500000,
    location: "Malibu, California",
    latitude: 34.0259,
    longitude: -118.7798,
    size: 2500,
    bedrooms: 4,
    bathrooms: 3,
    images: [
      ""
    ],
  },
  {
    id: 4,
    title: "Modern Loft in Downtown",
    description:
      "A stylish loft with an open floor plan and floor-to-ceiling windows.",
    type: "loft",
    price: 275000,
    location: "Downtown, Los Angeles",
    latitude: 34.0522,
    longitude: -118.2437,
    size: 1000,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://example.com/penthouse1.jpg",
      "https://example.com/penthouse1.jpg",
    ],
  },
  {
    id: 5,
    title: "Rustic Farmhouse with Orchard",
    description:
      "A beautiful farmhouse with an orchard and a charming rustic interior.",
    type: "farmhouse",
    price: 200000,
    location: "Napa Valley, California",
    latitude: 38.2975,
    longitude: -122.2869,
    size: 2000,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      "https://example.com/penthouse1.jpg",
      "https://example.com/farmhouse2.jpg",
    ],
  },
  {
    id: 6,
    title: "HIPenthouse Apartment with Skyline View",
    description:
      "An elegant penthouse with panoramic views of the city skyline.",
    type: "penthouse",
    price: 450000,
    location: "Downtown, Chicago",
    latitude: 41.8781,
    longitude: -87.6298,
    size: 1800,
    bedrooms: 3,
    bathrooms: 2,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC03cpkicW91pSxYOap9orpiPDAuTUeRM6dw&s",
      "https://images.inc.com/uploaded_files/image/1920x1080/getty_164107628_970647970450057_56760.jpg",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhfd14-Fsn8h_ihNm5E6I7XmoRhgaFAcDfmA&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoEaAv4KZ_JoT3OZnEcbBHabim8ajlxQXAxw&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTta0XsQDICRBsKhhCivnBCRkL3KDsfAc66jg&s",
      "https://img.staticmb.com/mbcontent/images/crop/uploads/2024/6/legal-documents-required-to-buy-property-in-india_0_1200.jpg"
    ],
  },
  {
    id: 7,
    title: "Historic Townhouse in Quiet Neighborhood",
    description:
      "A charming townhouse with historical features in a peaceful area.",
    type: "townhouse",
    price: 300000,
    location: "Brooklyn, New York",
    latitude: 40.6782,
    longitude: -73.9442,
    size: 1600,
    bedrooms: 2,
    bathrooms: 2,
    images: [
      "https://example.com/townhouse1.jpg",
      "https://example.com/townhouse2.jpg",
    ],
  },
  {
    id: 8,
    title: "Eco-Friendly Tiny Home",
    description:
      "A compact, eco-friendly tiny home with solar power and green features.",
    type: "tiny home",
    price: 80000,
    location: "Portland, Oregon",
    latitude: 45.5152,
    longitude: -122.6784,
    size: 400,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://example.com/tinyhome1.jpg",
      "https://example.com/tinyhome2.jpg",
    ],
  },
  {
    id: 9,
    title: "Luxury Villa with Garden",
    description:
      "A grand villa with a beautiful garden and spacious interiors.",
    type: "villa",
    price: 600000,
    location: "Palm Beach, Florida",
    latitude: 26.7056,
    longitude: -80.0364,
    size: 3000,
    bedrooms: 5,
    bathrooms: 4,
    images: [
      "https://example.com/luxuryvilla1.jpg",
      "https://example.com/luxuryvilla2.jpg",
    ],
  },
  {
    id: 10,
    title: "Studio Apartment with Balcony",
    description: "A compact studio with a balcony, perfect for city living.",
    type: "studio",
    price: 150000,
    location: "San Francisco, California",
    latitude: 37.7749,
    longitude: -122.4194,
    size: 500,
    bedrooms: 1,
    bathrooms: 1,
    images: [
      "https://example.com/studio1.jpg",
      "https://example.com/studio2.jpg",
    ],
  },
];

export const SingleList = {
  id: 1,
  title: "Luxury Condo Near Central Park",
  description:
    "A luxurious condo with breathtaking park views and modern amenities.",
  type: "condo",
  price: 350000,
  location: "Central Park, New York",
  latitude: 40.7812,
  longitude: -73.9665,
  size: 1500,
  bedrooms: 2,
  bathrooms: 2,
  images: [
    "https://img.staticmb.com/mbcontent/images/crop/uploads/2024/6/legal-documents-required-to-buy-property-in-india_0_1200.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC03cpkicW91pSxYOap9orpiPDAuTUeRM6dw&s",
    "https://images.inc.com/uploaded_files/image/1920x1080/getty_164107628_970647970450057_56760.jpg",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhfd14-Fsn8h_ihNm5E6I7XmoRhgaFAcDfmA&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoEaAv4KZ_JoT3OZnEcbBHabim8ajlxQXAxw&s",
    "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTta0XsQDICRBsKhhCivnBCRkL3KDsfAc66jg&s",    
  ],
};
